# Use official Python 3.9.12 slim image
FROM python:3.9.12-slim

# Set working directory
WORKDIR /app

# Copy requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --upgrade pip \
    && pip install -r requirements.txt --prefer-binary

# Copy the rest of the application
COPY . .

# Run the application
CMD ["gunicorn", "--bind", "0.0.0.0:$PORT", "aqi_prediction:app"]