# render.yaml
prebuild:
  - pip install --upgrade pip  # Optional: Upgrade pip to the latest version
  - pip install -r requirements.txt  # Use pre-built wheels
build:
  python_version: "3.9.12"
services:
  - type: web
    name: air-quality-monitor
    env: python
    buildCommand: "pip install -r requirements.txt"  # Single corrected command
    startCommand: "gunicorn --bind 0.0.0.0:$PORT aqi_prediction:app"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.12"