# render.yaml
prebuild:
  - pip install -r requirements.txt
build:
  python_version: "3.9.12"
services:
  - type: web
    name: air-quality-monitor
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT aqi_prediction:app"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.12"